### PR TITLE
Multiple tables

### PR DESCRIPTION
**Pull request by frempongdev**
### - Added Multiple Tables and referenced them as relations.
  - [Created owners Table](https://github.com/frempongdev/Vet-Clinic/commit/6e36f5ab017530a7ac32e59c55f933b62a2963f8)
image
  - [Created species Table](https://github.com/frempongdev/Vet-Clinic/commit/fad41953688c016d9a092b08e51528cc0f425123)
image
image
  - [Removed species column from animals Table](https://github.com/frempongdev/Vet-Clinic/commit/78df38872cad2fee9537ca8ac9e9446f8a297d7c)
image
  - [Added species_id column to animals table with reference to species table](https://github.com/frempongdev/Vet-Clinic/commit/aebe689bb02a02df3a81de5ee73a666f45f28a88)
image
  - [Added owners_id column to animals table with reference to owners table](https://github.com/frempongdev/Vet-Clinic/commit/7093006ad8ee576fb0509b5342aab3fb6ce8f607)
image
_updated new tables_
  - [Inserted data into owners Table](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/e06382ed36894170992ee3a85c948d2428243152)
image
  - [Inserted data into species Table](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/55a9f98e0409fab06ea230a168a2730afc99b3dd)
image
  - [Update animals Table with species_id reference from species Table](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/ca4dd55a46e3ed064cf4ebb8f4293a7b8f855f29)
image
  - [Added correct Query for species_id updates](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/ccebbeac66fdbfbb58a036ed24bc1146656eaec1)
image
image
image
  - [Updated animals Table with owners_id reference from owners Table](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/0f01e0dd8430e2931624ea1f63ef5e2cf7a131ca)
image
image
image
image
image
_queries_
  - [Add query to check animals owned by Melody Pond](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/6d776fabaa241cd17b219eab70d2480744f7ee51)
image
  - [Add query to check all Pokemon animals](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/542cf3969dc22e32d3a8517576825fd3aa8eda3e)
image
  - [Add query to list all owners and their animals](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/812c22cb5f539d59296bee1ae1b57f5021c24000)
image
  - [Add query to list How many animals are there per species](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/8eb8fee5cad674e996ee39c96744743a1bffce7f)
image
  - [Add query to list all Digimons owned by Jennifer Orwell](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/a6a4993011d75b3a101ddfa0a10c777d68583ce8)
image
  - [Add query to list all non-escaped animals of Dean Winchester](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/4635ed66e31f665858242b5e6d9e47ffc3edea5b)
image
  - [Add query to check who owns the most animals](https://github.com/frempongdev/Vet-Clinic/pull/3/commits/9cab2d9a6616222b00bda6678ef027bbf6143a4e)
image

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Frempong, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
  * Kindly ensure to include the _License_ section to your ReadMe.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by frempongdev** [comment]
Hi @rloterh ,
Thank You for your review. My understanding of the instructions given for this projects was no to add any other file until asked to do so. 

This is the reason why I omitted the License file.

**Review by BertrandConxy — APPROVED** [review]
Hi @frempongdev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- No linter errors
- project requirements are met
- project works fine
- good PR description
- correct flow is used

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by frempongdev** [comment]
@BertrandConxy 
Thanks for approving this PR.

**Pull request merged**
