### PR TITLE
Animals table

### PR DESCRIPTION
**Pull request by frempongdev**
### - Created  Animals Table with Queries.
  - [Created Database vet_clinic](https://github.com/frempongdev/Vet-Clinic/commit/5aa89560e143a912080f4885a839b18b50ccfa58)
  - [Created Table animals with all columns](https://github.com/frempongdev/Vet-Clinic/commit/5ba21ef97d5022ef9335dc6e9804d4903968a19c)
  - [Inserted animal details into Table](https://github.com/frempongdev/Vet-Clinic/commit/dd3d629dc00b5472c774fb02615782e9a7c09769)
  - [Added queries for animals table](https://github.com/frempongdev/Vet-Clinic/commit/68c0790da0608dead411bcd68b50321490486c1c)
  - [Updated README.md](https://github.com/frempongdev/Vet-Clinic/commit/799a1de636ef0b350df9247faabf06c3b5cbb637)
  

### - Below are the various Queries and their corresponding screenshots.
  - SELECT * FROM animals;
image
  - SELECT * FROM animals WHERE name::text LIKE '%mon';
image
  - SELECT name FROM animals where date_of_birth BETWEEN '2016,01,01' AND '2019,01,01';
image
  - SELECT name FROM animals WHERE neutered = true AND escape_attempts < 3;
image
  - SELECT date_of_birth FROM animals WHERE name IN ('Agumon','Pikachu');
image
  - SELECT name,escape_attempts FROM animals WHERE weight_kg > 10.5;
image
  - SELECT * FROM animals WHERE neutered = true;
image
  - SELECT * FROM animals WHERE name NOT IN ('Gabumon');
image
  - SELECT * FROM animals WHERE weight_kg >= 10.4 AND weight_kg <=17.3;
image

### CODE REVIEW

**Review by omarsalem7 — CHANGES_REQUESTED** [review]
Hi @frempongdev 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

you-are-near

## Highlights
- The Pull Request has a proper title ✔️
- Correct git-flow ✔️

## Required Changes ♻️
- [x] Kindly consider adding screenshots for queries results in the pull request description

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by frempongdev** [comment]
Hi @omarsalem7,
Thanks for your reminder about the required screenshots for the queries.

Doing that immediately.

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @frempongdev,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

giphy (1)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by frempongdev** [comment]
@Omar-Muhamad ,
Thanks for taking a look at this PR and approving it. 👍🏿

**Pull request merged**
